import { NextRequest } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { authenticateApiRequest, apiError } from '@/lib/api-auth';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { persistSession: false } }
);

// GET /api/v1/coaching/sessions/:session_id/export — returns PDF of session transcript
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ session_id: string }> }
) {
  const auth = await authenticateApiRequest(req);
  if (!auth.ok) return auth.response;

  const { session_id } = await params;

  // Verify session belongs to user
  const { data: session } = await supabase
    .from('coaching_sessions')
    .select('id, persona_id, title, started_at, message_count')
    .eq('id', session_id)
    .eq('user_id', auth.userId)
    .maybeSingle();
  if (!session) return apiError('Session not found', 404, 'NOT_FOUND');

  const [messagesRes, personaRes] = await Promise.all([
    supabase
      .from('coaching_messages')
      .select('role, content, created_at')
      .eq('session_id', session_id)
      .order('created_at'),
    supabase
      .from('coach_personas')
      .select('name, avatar_emoji, tagline')
      .eq('id', session.persona_id)
      .maybeSingle(),
  ]);

  const messages = messagesRes.data ?? [];
  const persona = personaRes.data;

  // Build HTML for PDF (we render as HTML and let the browser print-to-PDF,
  // or use this as a clean text/html response for client-side printing)
  const sessionDate = new Date(session.started_at).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  const messageRows = messages.map((m) => {
    const isUser = m.role === 'user';
    const time = new Date(m.created_at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
    return `
      <div style="margin-bottom:16px; text-align:${isUser ? 'right' : 'left'}">
        <div style="display:inline-block; max-width:75%; padding:12px 16px; border-radius:16px;
          background:${isUser ? '#6A1B9A' : '#F3F4F6'}; color:${isUser ? '#fff' : '#111'};
          font-size:14px; line-height:1.6; border-bottom-${isUser ? 'right' : 'left'}-radius:4px;">
          ${escapeHtml(m.content)}
        </div>
        <div style="font-size:11px; color:#9CA3AF; margin-top:4px;">${time}</div>
      </div>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Coaching Session — ${session.title ?? 'Untitled'}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #111; }
    h1 { font-size: 22px; font-weight: 800; color: #6A1B9A; }
    .meta { font-size: 13px; color: #6B7280; margin-bottom: 32px; }
    .coach { background: #F5F3FF; border-radius: 12px; padding: 14px 18px; margin-bottom: 28px; display:flex; align-items:center; gap:12px; }
    .coach-name { font-weight: 700; color: #6A1B9A; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Coaching Session Transcript</h1>
  <div class="meta">${sessionDate} · ${messages.length} messages</div>
  ${persona ? `
  <div class="coach">
    <span style="font-size:28px">${persona.avatar_emoji}</span>
    <div>
      <div class="coach-name">${persona.name}</div>
      <div style="font-size:13px;color:#6B7280">${persona.tagline}</div>
    </div>
  </div>` : ''}
  <div>${messageRows}</div>
  <div style="margin-top:40px; padding-top:16px; border-top:1px solid #E5E7EB; font-size:11px; color:#9CA3AF; text-align:center;">
    Generated by Daily Activity Tracker · ${new Date().toLocaleDateString('en-IN')}
  </div>
</body>
</html>`;

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="coaching-session-${session_id.slice(0, 8)}.html"`,
    },
  });
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/\n/g, '<br>');
}
